name: 'Build Node'


on: 
  workflow_dispatch:
  push: 
    branches: 
      - wf-test

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        animal: [cat, dog, bear]
        color: [black, brown]
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.animal }}"
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: npm install
  #       run: |
  #         npm install
  #         npm run build
  #     - uses: actions/upload-artifact@main
  #       with:
  #         name: webpack artifacts
  #         path: public/
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/download-artifact@main
  #     with:
  #       name: webpack artifacts
  #       path: public
